### ISSUE TITLE
[BUG] Typo on pop up message "SUCCES"

### ISSUE THREAD

**Issue by AnjarTiyo** [Capstone-Group3-Mentutor/Front-End#71]
DearTeam FE,

I found following Bug related to typo

```
Step failed
org.junit.ComparisonFailure: expected:<Register Succes[s]> but was:<Register Succes[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at mentutor.StepDefs.RegisterUser.RegisterNewUserStepDef.registerSuccess(RegisterNewUserStepDef.java:33)
	at ✽.Registration Success(file:///home/anjar/alterra/Mentutor/QE-UI/src/test/resources/features/registerUser/registerNewUser.feature:82)

```

## Step to reproduce this bug:
1. Admin Register new user with valid data
2. When Admin click add button
3. Then Pop Up message appeared

## BUG ISSUE

Message should be **"Register Success"** but get **"Register Succes"**

## REFERENCE
https://www.oxfordlearnersdictionaries.com/definition/english/success?q=success

## TESTER POV
Element contain typo is **css=.swal2-title**

It is minor bug but will make Automation Test Assertion Error. So it is considered as Medium.

# Thanks You

**Comment by AnjarTiyo** [comment]
Dear Mbak @Annisaard and Mas @FaturFawkes, please note me regarding this bug fixing status. thanks

**Comment by Dwifakhri** [comment]
Dear Mas @AnjarTiyo , thank you for the information,
Based on that issue, we've already noticed and fixed it. (wait to be deploy)
Thank You
